# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c4416095157e75b8da55e1037976dc63"
name = "SocioShare"
application_url = "https://web-production-ffa40.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2024-01"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://web-production-ffa40.up.railway.app/api/webhooks/customers/data_request"
  customer_data_request_url = "https://web-production-ffa40.up.railway.app/api/webhooks/customers/redact"
  shop_deletion_url = "https://web-production-ffa40.up.railway.app/api/webhooks/shop/redact"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[auth]
redirect_urls = [ "https://web-production-ffa40.up.railway.app/api/auth/callback" ]
