client_id = ""
name = "SocioShare"
application_url = "https://localhost:3000"
embedded = true

[build]
automatically_update_urls_on_dev = true

[auth]
redirect_urls = ["https://localhost:3000/api/auth/callback"]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[access_scopes]
scopes = "read_products"
